import blogImg from "../../public/images/sliderImg.png"

const BLOGS_DATA = [
  {
    id: 1,
    textHeading: "Interview with Aditya Nighhot",
    slug: `interview-with-aditya-nighhot1`,
    img: blogImg,
    date: "Sep 30th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `In today's world, people often feel the lack of time to embodiment everything desired in reality. Of course, a person can adapt to such conditions through proper planning and good use of their own capabilities, forces, resources. But sometimes, it happens that people postpone the execution of some planned tasks "for later." For example, students often delay writing  several other assignments to solve.`,
  },
  {
    id: 2,
    textHeading: "Interview with Ghazala Anjum | Pristine Books",
    slug: `interview-with-ghazala-anjum2`,
    img: blogImg,
    date: "Jul 23rd 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Writing is not limited to jotting down your experience or thoughts on paper and just putting it out. Every author needs to remember that it needs to be valuable and of providing insights to its readers. It should be able to carve a lasting remark, the process of which begins way early than even writing itself. Here is when book marketing comes into the picture. Book marketing is very salient for authors, and in this article, I am throwing light on some of them`,
  },
  {
    id: 3,
    textHeading: "Interview with William J. Goyette",
    slug: `interview-with-william-j-goyette3`,
    img: blogImg,
    date: "Jul 21st 2021",
    author: "Akansha Jain",
    views: 178,
    content: `We live in a world where we constantly face chaos and negativity. Switch on your television, tune into any news channel, and bad news is always there. In our personal lives, we are always grappling with the need to keep everything balanced. When we set one thing right, another goes wrong. Anxiety and depression start to take over our minds`,
  },
  {
    id: 4,
    textHeading: "Interview with Sebastian Schug",
    slug: `interview-with-sebastian-schug4`,
    img: blogImg,
    date: "May 5th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Are you one of those who finds writing book reports a tedious activity? You’ll change your opinion when you find out how many exciting and fun ways to present a book report. You should use all your imagination as a`,
  },
  {
    id: 5,
    textHeading: "Interview with Aditya Nighhot",
    slug: `interview-with-aditya-nighhot5`,
    img: blogImg,
    date: "Sep 30th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `In today's world, people often feel the lack of time to embodiment everything desired in reality. Of course, a person can adapt to such conditions through proper planning and good use of their own capabilities, forces, resources. But sometimes, it happens that people postpone the execution of some planned tasks "for later." For example, students often delay writing  several other assignments to solve.`,
  },
  {
    id: 6,
    textHeading: "Interview with Ghazala Anjum | Pristine Books",
    slug: `interview-with-ghazala-anjum6`,
    img: blogImg,
    date: "Jul 23rd 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Writing is not limited to jotting down your experience or thoughts on paper and just putting it out. Every author needs to remember that it needs to be valuable and of providing insights to its readers. It should be able to carve a lasting remark, the process of which begins way early than even writing itself. Here is when book marketing comes into the picture. Book marketing is very salient for authors, and in this article, I am throwing light on some of them`,
  },
  {
    id: 7,
    textHeading: "Interview with William J. Goyette",
    slug: `interview-with-william-j-goyette7`,
    img: blogImg,
    date: "Jul 21st 2021",
    author: "Akansha Jain",
    views: 178,
    content: `We live in a world where we constantly face chaos and negativity. Switch on your television, tune into any news channel, and bad news is always there. In our personal lives, we are always grappling with the need to keep everything balanced. When we set one thing right, another goes wrong. Anxiety and depression start to take over our minds`,
  },
  {
    id: 8,
    textHeading: "Interview with Sebastian Schug",
    slug: `interview-with-sebastian-schug8`,
    img: blogImg,
    date: "May 5th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Are you one of those who finds writing book reports a tedious activity? You’ll change your opinion when you find out how many exciting and fun ways to present a book report. You should use all your imagination as a`,
  },
  {
    id: 9,
    textHeading: "Interview with Aditya Nighhot",
    slug: `interview-with-aditya-nighhot9`,
    img: blogImg,
    date: "Sep 30th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `In today's world, people often feel the lack of time to embodiment everything desired in reality. Of course, a person can adapt to such conditions through proper planning and good use of their own capabilities, forces, resources. But sometimes, it happens that people postpone the execution of some planned tasks "for later." For example, students often delay writing  several other assignments to solve.`,
  },
  {
    id: 10,
    textHeading: "Interview with Ghazala Anjum | Pristine Books",
    slug: `interview-with-ghazala-anjum10`,
    img: blogImg,
    date: "Jul 23rd 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Writing is not limited to jotting down your experience or thoughts on paper and just putting it out. Every author needs to remember that it needs to be valuable and of providing insights to its readers. It should be able to carve a lasting remark, the process of which begins way early than even writing itself. Here is when book marketing comes into the picture. Book marketing is very salient for authors, and in this article, I am throwing light on some of them`,
  },
  {
    id: 11,
    textHeading: "Interview with William J. Goyette",
    slug: `interview-with-william-j-goyette11`,
    img: blogImg,
    date: "Jul 21st 2021",
    author: "Akansha Jain",
    views: 178,
    content: `We live in a world where we constantly face chaos and negativity. Switch on your television, tune into any news channel, and bad news is always there. In our personal lives, we are always grappling with the need to keep everything balanced. When we set one thing right, another goes wrong. Anxiety and depression start to take over our minds`,
  },
  {
    id: 12,
    textHeading: "Interview with Sebastian Schug",
    slug: `interview-with-sebastian-schug12`,
    img: blogImg,
    date: "May 5th 2021",
    author: "Akansha Jain",
    views: 178,
    content: `Are you one of those who finds writing book reports a tedious activity? You’ll change your opinion when you find out how many exciting and fun ways to present a book report. You should use all your imagination as a`,
  },
];

export default BLOGS_DATA;
