import bookCoverImg from "../../public/images/bookCoverImg.png";

const BOOKCOVER_DATA = [
  {
    id: 1,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest1`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties1`,
  },
  {
    id: 2,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest2`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties2`,
  },
  {
    id: 3,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest3`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties3`,
  },
  {
    id: 4,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest4`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties4`,
  },
  {
    id: 5,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest5`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties5`,
  },
  {
    id: 6,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest6`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties6`,
  },
  {
    id: 7,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest7`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties7`,
  },
  {
    id: 8,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest8`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties8`,
  },
  {
    id: 9,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest9`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties9`,
  },
  {
    id: 10,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    textHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest10`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties10`,
  },
  {
    id: 11,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    texttextHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest11`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties11`,
  },
  {
    id: 12,
    img: bookCoverImg,
    bookCategory: "Fantasy",
    texttextHeading: `The Cardinal War by Jennifer Tempest`,
    slug: `the-cardinal-war-by-jennifer-tempest12`,
    date: "Feb 10th 2022",
    author: "Akansha Jain",
    views: 178,
    content: `This short Fantasy fiction revolves around four noble houses and their ambitions to make their house prominent. But unfortunately, only one could win and claim the seat of Mordale, which led to the war and endless casualties12`,
  },
];

export default BOOKCOVER_DATA;